/*
 Navicat Premium Data Transfer

 Source Server         : antstar-dev-test
 Source Server Type    : MySQL
 Source Server Version : 50731
 Source Host           : 81.71.139.143:8306
 Source Schema         : cloud-nacos

 Target Server Type    : MySQL
 Target Server Version : 50731
 File Encoding         : 65001

 Date: 05/04/2021 23:26:48
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 57 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (12, 'cloud-common-redis.properties', 'DEFAULT_GROUP', 'spring.redis.host=81.71.139.143\r\nspring.redis.port=8379\r\nspring.redis.password=antstar\r\nspring.redis.database=2', '09fb48559f357d81702b0f051793b450', '2021-03-21 03:25:02', '2021-03-21 03:25:02', NULL, '172.18.0.1', '', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47', 'redis configuration', NULL, NULL, 'properties', NULL);
INSERT INTO `config_info` VALUES (24, 'cloud-common-mybatis-plus.properties', 'DEFAULT_GROUP', '# xml 扫描路径\r\nmybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml\r\n\r\n# MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)\r\nmybatis-plus.typeAliasesPackage=com.fank243.cloud.component.domain.entity\r\n\r\n# 枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性\r\nmybatis-plus.typeEnumsPackage=com.fank243.cloud.component.domain.enums\r\n\r\n# # 全局默认主键类型，NONE：随机ID，默认值：ASSIGN_ID(雪花算法)\r\nmybatis-plus.global-config.db-configid-type=NONE\r\n\r\n# 表名前缀\r\nmybatis-plus.global-config.table-prefix=tb\r\n\r\n# 逻辑删除字段名称\r\nmybatis-plus.global-configlogic-delete-field=is_deleted \r\n\r\n # 字段验证策略之 insert,在 insert 的时候的字段验证策略\r\nmybatis-plus.global-configinsert-strategy=not_empty\r\n\r\n# 字段验证策略之 update,在 update 的时候的字段验证策略\r\nmybatis-plus.global-configupdate-strategy=not_empty \r\n\r\n# 开启Mybatis二级缓存，默认为 true\r\nmybatis-plus.configuration.cache-enabled=false\r\n', 'c832f393bc3ed731981c3b5dc6271a75', '2021-03-24 09:35:11', '2021-03-24 09:35:11', NULL, '172.18.0.1', '', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47', NULL, NULL, NULL, 'properties', NULL);
INSERT INTO `config_info` VALUES (29, 'cloud-auth.properties', 'DEFAULT_GROUP', '# 数据源\r\nspring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-auth\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', '3a1467cac417c0a430b7f2bbc427a1ab', '2021-03-25 11:29:20', '2021-03-25 11:29:20', NULL, '172.18.0.1', '', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47', NULL, NULL, NULL, 'properties', NULL);
INSERT INTO `config_info` VALUES (34, 'cloud-gateway-dev.yml', 'DEFAULT_GROUP', 'spring:\n  redis:\n    host: 81.71.139.143\n    port: 8379\n    password: antstar\n    database: 2\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: ruoyi-auth\n          uri: lb://ruoyi-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: ruoyi-gen\n          uri: lb://ruoyi-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: ruoyi-job\n          uri: lb://ruoyi-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: ruoyi-system\n          uri: lb://ruoyi-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 文件服务\n        - id: ruoyi-file\n          uri: lb://ruoyi-file\n          predicates:\n            - Path=/file/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', '3ff515fa29464d4ecd326b46ef4130b7', '2021-04-04 09:59:56', '2021-04-04 09:59:56', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (35, 'cloud-auth-dev.yml', 'DEFAULT_GROUP', 'spring: \n  redis:\n    host: 81.71.139.143\n    port: 8379\n    password: antstar\n    database: 2\n', '09564dc7ddcb01ae832df79f392263dd', '2021-04-04 10:06:23', '2021-04-04 10:06:23', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (36, 'cloud-monitor-dev.yml', 'DEFAULT_GROUP', '# spring\r\nspring: \r\n  security:\r\n    user:\r\n      name: ruoyi\r\n      password: 123456\r\n  boot:\r\n    admin:\r\n      ui:\r\n        title: 若依服务状态监控\r\n', 'd8997d0707a2fd5d9fc4e8409da38129', '2021-04-04 10:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (37, 'cloud-system-dev.yml', 'DEFAULT_GROUP', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource:\r\n    druid:\r\n      stat-view-servlet:\r\n        enabled: true\r\n        loginUsername: admin\r\n        loginPassword: 123456\r\n    dynamic:\r\n      druid:\r\n        initial-size: 5\r\n        min-idle: 5\r\n        maxActive: 20\r\n        maxWait: 60000\r\n        timeBetweenEvictionRunsMillis: 60000\r\n        minEvictableIdleTimeMillis: 300000\r\n        validationQuery: SELECT 1 FROM DUAL\r\n        testWhileIdle: true\r\n        testOnBorrow: false\r\n        testOnReturn: false\r\n        poolPreparedStatements: true\r\n        maxPoolPreparedStatementPerConnectionSize: 20\r\n        filters: stat,wall,slf4j\r\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\r\n      datasource:\r\n          # 主库数据源\r\n          master:\r\n            driver-class-name: com.mysql.cj.jdbc.Driver\r\n            url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            username: root\r\n            password: password\r\n          # 从库数据源\r\n          # slave:\r\n            # username: \r\n            # password: \r\n            # url: \r\n            # driver-class-name: \r\n      # seata: true    # 开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭\r\n\r\n# seata配置\r\nseata:\r\n  # 默认关闭，如需启用spring.datasource.dynami.seata需要同时开启\r\n  enabled: false\r\n  # Seata 应用编号，默认为 ${spring.application.name}\r\n  application-id: ${spring.application.name}\r\n  # Seata 事务组编号，用于 TC 集群名\r\n  tx-service-group: ${spring.application.name}-group\r\n  # 关闭自动代理\r\n  enable-auto-data-source-proxy: false\r\n  # 服务配置项\r\n  service:\r\n    # 虚拟组和分组的映射\r\n    vgroup-mapping:\r\n      ruoyi-system-group: default\r\n  config:\r\n    type: nacos\r\n    nacos:\r\n      serverAddr: 127.0.0.1:8848\r\n      group: SEATA_GROUP\r\n      namespace:\r\n  registry:\r\n    type: nacos\r\n    nacos:\r\n      application: seata-server\r\n      server-addr: 127.0.0.1:8848\r\n      namespace:\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.system\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip', 'ac8913dee679e65bb7d482df5f267d4e', '2021-04-04 10:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (38, 'cloud-gen-dev.yml', 'DEFAULT_GROUP', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource: \r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: password\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.gen.domain\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 代码生成接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n\r\n# 代码生成\r\ngen: \r\n  # 作者\r\n  author: ruoyi\r\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\r\n  packageName: com.ruoyi.system\r\n  # 自动去除表前缀，默认是false\r\n  autoRemovePre: false\r\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\r\n  tablePrefix: sys_\r\n', '8c79f64a4cca9b821a03dc8b27a2d8eb', '2021-04-04 10:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (39, 'cloud-job-dev.yml', 'DEFAULT_GROUP', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: password\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.job.domain\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 定时任务接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n', 'd6dfade9a2c93c463ae857cd503cb172', '2021-04-04 10:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (40, 'cloud-file-dev.yml', 'DEFAULT_GROUP', '# 本地文件上传    \r\nfile:\r\n    domain: http://127.0.0.1:9300\r\n    path: D:/ruoyi/uploadPath\r\n    prefix: /statics\r\n\r\n# FastDFS配置\r\nfdfs:\r\n  domain: http://8.129.231.12\r\n  soTimeout: 3000\r\n  connectTimeout: 2000\r\n  trackerList: 8.129.231.12:22122\r\n\r\n# Minio配置\r\nminio:\r\n  url: http://8.129.231.12:9000\r\n  accessKey: minioadmin\r\n  secretKey: minioadmin\r\n  bucketName: test', '5382b93f3d8059d6068c0501fdd41195', '2021-04-04 10:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (42, 'cloud-gateway-sentinel', 'DEFAULT_GROUP', '[\r\n    {\r\n        \"resource\": \"ruoyi-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-system\",\r\n        \"count\": 1000,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-job\",\r\n        \"count\": 300,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]', '9f3a3069261598f74220bc47958ec252', '2021-04-04 10:09:41', '2021-04-04 10:09:41', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'json', NULL);
INSERT INTO `config_info` VALUES (43, 'cloud-common.yml', 'DEFAULT_GROUP', 'spring:\n  main:\n    allow-bean-definition-overriding: true\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n', 'c07e6f7321493f6d5390d0a08bffb75a', '2021-04-04 10:21:15', '2021-04-04 10:21:15', NULL, '172.18.0.1', '', '', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (44, 'cloud-common.properties', 'DEFAULT_GROUP', 'spring.main.allow-bean-definition-overriding=true\nspring.autoconfigure.exclude=com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon.ReadTimeout=10000\nribbon.ConnectTimeout=10000\n\n# feign 配置\nfeign.sentinel.enabled=true\nfeign.okhttp.enabled=true\nfeign.httpclient.enabled=false\nfeign.client.config.default.connectTimeout=10000\nfeign.client.config.default.readTimeout=10000\nfeign.compression.request.enabled=true\nfeign.compression.response.enabled=true\n\n# 暴露监控端点\nmanagement.endpoints.web.exposure.include=\'*\'\n', 'b62774df756eb9570ee7960d0ae2e86b', '2021-04-04 10:24:36', '2021-04-04 10:29:15', NULL, '172.18.0.1', '', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47', '', '', '', 'properties', '');
INSERT INTO `config_info` VALUES (46, 'cloud-gateway.properties', 'DEFAULT_GROUP', 'spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true\nspring.cloud.gateway.discovery.locator.enabled=true\n      \n# 不校验白名单\nignore.whites=/auth/logout,/auth/login,/*/v2/api-docs,/csrf\n', '141244852bf27e125cbb9480406db317', '2021-04-04 10:30:07', '2021-04-04 10:32:55', NULL, '172.18.0.1', '', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47', '', '', '', 'properties', '');
INSERT INTO `config_info` VALUES (48, 'cloud-common-redis.properties', 'DEFAULT_GROUP', 'spring.redis.host=81.71.139.143\r\nspring.redis.port=8379\r\nspring.redis.password=antstar\r\nspring.redis.database=2', '09fb48559f357d81702b0f051793b450', '2021-04-04 10:54:49', '2021-04-04 10:54:49', NULL, '172.18.0.1', '', 'b8ffe849-49ed-452f-86df-273cfc8301dc', NULL, NULL, NULL, 'properties', NULL);
INSERT INTO `config_info` VALUES (49, 'cloud-common-mybatis-plus.properties', 'DEFAULT_GROUP', '# xml 扫描路径\r\nmybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml\r\n\r\n# MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)\r\nmybatis-plus.typeAliasesPackage=com.fank243.cloud.component.domain.entity\r\n\r\n# 枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性\r\nmybatis-plus.typeEnumsPackage=com.fank243.cloud.component.domain.enums\r\n\r\n# # 全局默认主键类型，NONE：随机ID，默认值：ASSIGN_ID(雪花算法)\r\nmybatis-plus.global-config.db-configid-type=NONE\r\n\r\n# 表名前缀\r\nmybatis-plus.global-config.table-prefix=tb\r\n\r\n# 逻辑删除字段名称\r\nmybatis-plus.global-configlogic-delete-field=is_deleted \r\n\r\n # 字段验证策略之 insert,在 insert 的时候的字段验证策略\r\nmybatis-plus.global-configinsert-strategy=not_empty\r\n\r\n# 字段验证策略之 update,在 update 的时候的字段验证策略\r\nmybatis-plus.global-configupdate-strategy=not_empty \r\n\r\n# 开启Mybatis二级缓存，默认为 true\r\nmybatis-plus.configuration.cache-enabled=false\r\n', 'c832f393bc3ed731981c3b5dc6271a75', '2021-04-04 10:54:49', '2021-04-04 10:54:49', NULL, '172.18.0.1', '', 'b8ffe849-49ed-452f-86df-273cfc8301dc', NULL, NULL, NULL, 'properties', NULL);
INSERT INTO `config_info` VALUES (50, 'cloud-auth.properties', 'DEFAULT_GROUP', '# 数据源\r\nspring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-auth\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', '3a1467cac417c0a430b7f2bbc427a1ab', '2021-04-04 10:54:49', '2021-04-04 10:54:49', NULL, '172.18.0.1', '', 'b8ffe849-49ed-452f-86df-273cfc8301dc', NULL, NULL, NULL, 'properties', NULL);
INSERT INTO `config_info` VALUES (51, 'cloud-common.properties', 'DEFAULT_GROUP', 'spring.main.allow-bean-definition-overriding=true\nspring.autoconfigure.exclude=com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon.ReadTimeout=10000\nribbon.ConnectTimeout=10000\n\n# feign 配置\nfeign.sentinel.enabled=true\nfeign.okhttp.enabled=true\nfeign.httpclient.enabled=false\nfeign.client.config.default.connectTimeout=10000\nfeign.client.config.default.readTimeout=10000\nfeign.compression.request.enabled=true\nfeign.compression.response.enabled=true\n\n# 暴露监控端点\nmanagement.endpoints.web.exposure.include=*\n', '293b42192bd132d1b69b04f69c6ee8dd', '2021-04-04 10:54:49', '2021-04-05 09:20:48', NULL, '172.18.0.1', '', 'b8ffe849-49ed-452f-86df-273cfc8301dc', '', '', '', 'properties', '');
INSERT INTO `config_info` VALUES (52, 'cloud-gateway.properties', 'DEFAULT_GROUP', 'spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true\nspring.cloud.gateway.discovery.locator.enabled=true\n      \n# 不校验白名单\nignore.whites=/auth/logout,/auth/login,/*/v2/api-docs,/csrf\n', '141244852bf27e125cbb9480406db317', '2021-04-04 10:54:49', '2021-04-04 10:54:49', NULL, '172.18.0.1', '', 'b8ffe849-49ed-452f-86df-273cfc8301dc', NULL, NULL, NULL, 'properties', NULL);

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint(64) UNSIGNED NOT NULL,
  `nid` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 70 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (0, 1, 'cloud-common.properties', 'DEFAULT_GROUP', '', 'test: 123', '5e76b5e94b54e1372f8b452ef64dc55c', '2021-03-21 16:05:45', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 2, 'cloud-common-datasource.properties', 'DEFAULT_GROUP', '', 'spring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://localhost:3306/fank-cloud\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=root', 'd00b4cc68e39a811f3d21e1c9ec4bd27', '2021-03-21 16:05:45', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 3, 'cloud-common-nacos.properties', 'DEFAULT_GROUP', '', 'test=123', '794e861031e379f99d8de0e533d293e4', '2021-03-21 16:05:45', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 4, 'cloud-common-sentinel.properties', 'DEFAULT_GROUP', '', 'spring.cloud.sentinel.transport.dashboard=192.168.31.116:8858', '733ee187d2d5d311431f9bf284c2a3e0', '2021-03-21 16:05:45', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 5, 'cloud-common-jetcache.properties', 'DEFAULT_GROUP', '', 'test=123', '794e861031e379f99d8de0e533d293e4', '2021-03-21 16:05:46', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 6, 'cloud-gateway-sentinel-flow.json', 'DEFAULT_GROUP', '', '[{\n    \"resource\":\"/hello\",\n    \"limitApp\":\"default\",\n    \"grade\":1,\n    \"count\":1,\n    \"strategy\":0,\n    \"controlBehavior\":0,\n    \"clusterMode\":false\n}]', '8d1775abab0533043aa3299636a162ae', '2021-03-21 16:05:46', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 7, 'cloud-gateway-sentinel-degrade.json', 'DEFAULT_GROUP', '', '[\n  {\n    \"resource\": \"xxx-story-res\",\n    \"count\": 100,\n    \"grade\": 0,\n    \"timeWindow\": 30\n  }\n]', 'b37f547d94858f522bc74d9017f96945', '2021-03-21 16:05:46', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 8, 'cloud-gateway.properties', 'DEFAULT_GROUP', '', 'test.name=spring cloud gateway\n# 限流\nspring.cloud.sentinel.datasource.ds.nacos.data-id=cloud-gateway-sentinel-flow.json\nspring.cloud.sentinel.datasource.ds.nacos.namespace=f1aa413a-d6d6-449f-82b2-315ccb7302a4\nspring.cloud.sentinel.datasource.ds.nacos.data-type=json\nspring.cloud.sentinel.datasource.ds.nacos.rule-type=flow\n\n# 熔断\nspring.cloud.sentinel.datasource.ds.nacos.data-id=cloud-gateway-sentinel-degrade.json\nspring.cloud.sentinel.datasource.ds.nacos.namespace=f1aa413a-d6d6-449f-82b2-315ccb7302a4\nspring.cloud.sentinel.datasource.ds.nacos.data-type=json\nspring.cloud.sentinel.datasource.ds.nacos.rule-type=degrade', 'f6c2d513e4fa7938410ea8316e797228', '2021-03-21 16:05:46', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 9, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"route_id\":\"cloud-auth-oauth2\",\"uri\":\"lb://cloud-auth-oauth2\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/oauth/**\"}}],\"filters\": []}]', '509c9229bff3b5848c5b7ed3b6100170', '2021-03-21 16:05:46', '2021-03-21 03:05:44', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (2, 10, 'cloud-common-datasource.properties', 'DEFAULT_GROUP', '', 'spring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://localhost:3306/fank-cloud\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=root', 'd00b4cc68e39a811f3d21e1c9ec4bd27', '2021-03-21 16:18:47', '2021-03-21 03:18:45', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (8, 11, 'cloud-gateway.properties', 'DEFAULT_GROUP', '', 'test.name=spring cloud gateway\n# 限流\nspring.cloud.sentinel.datasource.ds.nacos.data-id=cloud-gateway-sentinel-flow.json\nspring.cloud.sentinel.datasource.ds.nacos.namespace=f1aa413a-d6d6-449f-82b2-315ccb7302a4\nspring.cloud.sentinel.datasource.ds.nacos.data-type=json\nspring.cloud.sentinel.datasource.ds.nacos.rule-type=flow\n\n# 熔断\nspring.cloud.sentinel.datasource.ds.nacos.data-id=cloud-gateway-sentinel-degrade.json\nspring.cloud.sentinel.datasource.ds.nacos.namespace=f1aa413a-d6d6-449f-82b2-315ccb7302a4\nspring.cloud.sentinel.datasource.ds.nacos.data-type=json\nspring.cloud.sentinel.datasource.ds.nacos.rule-type=degrade', 'f6c2d513e4fa7938410ea8316e797228', '2021-03-21 16:19:18', '2021-03-21 03:19:16', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 12, 'cloud-common-redis.properties', 'DEFAULT_GROUP', '', 'spring.redis.host=81.71.139.143\r\nspring.redis.port=8379\r\nspring.redis.password=antstar\r\nspring.redis.database=2', '09fb48559f357d81702b0f051793b450', '2021-03-21 16:25:04', '2021-03-21 03:25:02', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 13, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"route_id\":\"cloud-auth-oauth2\",\"uri\":\"lb://cloud-auth-oauth2\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/oauth/**\"}}],\"filters\": []}]', '509c9229bff3b5848c5b7ed3b6100170', '2021-03-21 16:44:18', '2021-03-21 03:44:17', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 14, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-oauth2\",\"uri\":\"lb://cloud-auth-oauth2\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/oauth/**\"}}],\"filters\": []}]', 'e57e6760e47b803f9127aab5afbe6755', '2021-03-21 16:48:23', '2021-03-21 03:48:21', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 15, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-oauth2\",\"uri\":\"lb://cloud-auth-oauth2\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/oauth/**\"}}],\"filters\": []}]', 'e57e6760e47b803f9127aab5afbe6755', '2021-03-21 16:50:16', '2021-03-21 03:50:14', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 16, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-oauth2\",\"uri\":\"lb://cloud-auth-oauth2\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/oauth/**\"}}],\"filters\": []}]', 'e57e6760e47b803f9127aab5afbe6755', '2021-03-21 16:50:17', '2021-03-21 03:50:06', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 17, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-oauth2\",\"uri\":\"lb://cloud-auth-oauth2\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/oauth/**\"}}],\"filters\": []}]', 'e57e6760e47b803f9127aab5afbe6755', '2021-03-21 16:52:05', '2021-03-21 03:52:03', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 18, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[\n    {\n        \"id\": \"cloud-auth-oauth2\", \n        \"uri\": \"lb://cloud-auth-oauth2\", \n        \"order\": 0, \n        \"predicates\": [\n            {\n                \"name\": \"Path\", \n                \"args\": {\n                    \"pattern\": \"/api/oauth/**\"\n                }\n            }\n        ], \n        \"filters\": [ ]\n    },\n    {\n        \"id\": \"cloud-service-user\", \n        \"uri\": \"lb://cloud-service-user\", \n        \"order\": 0, \n        \"predicates\": [\n            {\n                \"name\": \"Path\", \n                \"args\": {\n                    \"pattern\": \"/api/user/**\"\n                }\n            }\n        ], \n        \"filters\": [ ]\n    }\n]', '41033d2adb3a125256d75e61c6789dfe', '2021-03-21 16:59:04', '2021-03-21 03:59:03', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 19, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-oauth2\",\"uri\":\"lb://cloud-auth-oauth2\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/oauth/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', 'a60f71ee87da6bfef591727ebfd07152', '2021-03-21 17:00:02', '2021-03-21 04:00:01', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (2, 20, 'cloud-common-datasource.properties', 'DEFAULT_GROUP', '', 'spring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-gateway\nspring.datasource.druid.username=root\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', 'd3bda797e868d417308b6c0a1d532420', '2021-03-21 17:01:43', '2021-03-21 04:01:42', NULL, '172.18.0.1', 'D', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 21, 'cloud-auth.properties', 'DEFAULT_GROUP', '', '# 数据源\r\nspring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-auth\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', '3a1467cac417c0a430b7f2bbc427a1ab', '2021-03-21 21:45:43', '2021-03-21 08:45:41', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 22, 'cloud-auth-shiro.properties', 'DEFAULT_GROUP', '', '# 数据源\r\nspring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-auth\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', '3a1467cac417c0a430b7f2bbc427a1ab', '2021-03-21 21:48:53', '2021-03-21 08:48:51', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (20, 23, 'cloud-auth.properties', 'DEFAULT_GROUP', '', '# 数据源\r\nspring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-auth\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', '3a1467cac417c0a430b7f2bbc427a1ab', '2021-03-21 21:48:58', '2021-03-21 08:48:56', NULL, '172.18.0.1', 'D', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 24, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-oauth2\",\"uri\":\"lb://cloud-auth-oauth2\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/oauth/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":1,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', '53278c1b1dd9dfd74fd7ee14b9ed6e5c', '2021-03-21 21:49:46', '2021-03-21 08:49:43', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 25, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-shiro\",\"uri\":\"lb://cloud-auth-shiro\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":1,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', 'c045e5920335f13aaeee257bec30520b', '2021-03-23 22:05:26', '2021-03-23 09:05:25', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 26, 'cloud-common-mybatis-plus.properties', 'DEFAULT_GROUP', '', '# xml 扫描路径\r\nmybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml\r\n\r\n# MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)\r\nmybatis-plus.typeAliasesPackage=com.fank243.cloud.component.domain.entity\r\n\r\n# 枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性\r\nmybatis-plus.typeEnumsPackage=com.fank243.cloud.component.domain.enums\r\n\r\n# # 全局默认主键类型，NONE：随机ID，默认值：ASSIGN_ID(雪花算法)\r\nmybatis-plus.global-config.db-configid-type=NONE\r\n\r\n# 表名前缀\r\nmybatis-plus.global-config.table-prefix=tb\r\n\r\n# 逻辑删除字段名称\r\nmybatis-plus.global-configlogic-delete-field=is_deleted \r\n\r\n # 字段验证策略之 insert,在 insert 的时候的字段验证策略\r\nmybatis-plus.global-configinsert-strategy=not_empty\r\n\r\n# 字段验证策略之 update,在 update 的时候的字段验证策略\r\nmybatis-plus.global-configupdate-strategy=not_empty \r\n\r\n# 开启Mybatis二级缓存，默认为 true\r\nmybatis-plus.configuration.cache-enabled=false\r\n', 'c832f393bc3ed731981c3b5dc6271a75', '2021-03-24 22:35:11', '2021-03-24 09:35:11', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 27, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-shiro\",\"uri\":\"lb://cloud-auth-shiro\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/auth/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":2}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":1,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', 'f721d16eb578f53c86f7ec7d643e7e75', '2021-03-24 23:42:27', '2021-03-24 10:42:27', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 28, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-shiro\",\"uri\":\"lb://cloud-auth-shiro\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/auth/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":1,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', '446782791ae33cad877954af2d51f963', '2021-03-25 00:04:57', '2021-03-24 11:04:53', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 29, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth\",\"uri\":\"lb://cloud-auth-shiro\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/auth/**\",}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}{\"id\":\"cloud-auth-shiro\",\"uri\":\"lb://cloud-auth-shiro\",\"order\":2\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/test/**\",}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":1,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', 'd90f86658741a69b8af58a16b11a7147', '2021-03-25 00:06:07', '2021-03-24 11:06:07', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 30, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth-shiro\",\"uri\":\"lb://cloud-auth-shiro\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/auth/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":2}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":1,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', 'f721d16eb578f53c86f7ec7d643e7e75', '2021-03-25 00:07:41', '2021-03-24 11:07:40', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 31, 'cloud-auth.properties', 'DEFAULT_GROUP', '', '# 数据源\r\nspring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-auth\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', '3a1467cac417c0a430b7f2bbc427a1ab', '2021-03-26 00:29:20', '2021-03-25 11:29:20', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (21, 32, 'cloud-auth-shiro.properties', 'DEFAULT_GROUP', '', '# 数据源\r\nspring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-auth\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', '3a1467cac417c0a430b7f2bbc427a1ab', '2021-03-26 00:29:26', '2021-03-25 11:29:26', NULL, '172.18.0.1', 'D', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 33, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth\",\"uri\":\"lb://cloud-auth-shiro\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/auth/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-auth-shiro\",\"uri\":\"lb://cloud-auth-shiro\",\"order\":2,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/test/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":1,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', '9f25df3a4e3394957015930b35dc8994', '2021-03-29 00:19:56', '2021-03-28 11:19:57', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (9, 34, 'cloud-gateway-router', 'DEFAULT_GROUP', '', '[{\"id\":\"cloud-auth\",\"uri\":\"lb://cloud-auth\",\"order\":0,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/auth/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-auth\",\"uri\":\"lb://cloud-auth\",\"order\":2,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/test/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]},{\"id\":\"cloud-service-user\",\"uri\":\"lb://cloud-service-user\",\"order\":1,\"predicates\":[{\"name\":\"Path\",\"args\":{\"pattern\":\"/api/user/**\"}}],\"filters\":[{\"name\":\"StripPrefix\",\"args\":{\"parts\":1}}]}]', '05bf8b0e478f81951e734b749b77fc27', '2021-03-29 00:23:22', '2021-03-28 11:23:23', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (2, 35, 'ruoyi-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: ruoyi-auth\r\n          uri: lb://ruoyi-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            # 验证码处理\r\n            - CacheRequestFilter\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: ruoyi-gen\r\n          uri: lb://ruoyi-gen\r\n          predicates:\r\n            - Path=/code/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 定时任务\r\n        - id: ruoyi-job\r\n          uri: lb://ruoyi-job\r\n          predicates:\r\n            - Path=/schedule/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: ruoyi-system\r\n          uri: lb://ruoyi-system\r\n          predicates:\r\n            - Path=/system/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 文件服务\r\n        - id: ruoyi-file\r\n          uri: lb://ruoyi-file\r\n          predicates:\r\n            - Path=/file/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n', 'ef4a58daf989827334b3aac1c9d68392', '2021-04-04 22:11:12', '2021-04-04 09:11:11', NULL, '172.18.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (3, 36, 'ruoyi-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n', 'b7354e1eb62c2d846d44a796d9ec6930', '2021-04-04 22:12:19', '2021-04-04 09:12:19', NULL, '172.18.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 37, 'cloud-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: 81.71.139.143\n    port: 8379\n    password: antstar\n    database: 2\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: ruoyi-auth\n          uri: lb://ruoyi-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: ruoyi-gen\n          uri: lb://ruoyi-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: ruoyi-job\n          uri: lb://ruoyi-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: ruoyi-system\n          uri: lb://ruoyi-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 文件服务\n        - id: ruoyi-file\n          uri: lb://ruoyi-file\n          predicates:\n            - Path=/file/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', '3ff515fa29464d4ecd326b46ef4130b7', '2021-04-04 22:59:56', '2021-04-04 09:59:56', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (2, 38, 'ruoyi-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: 81.71.139.143\n    port: 8379\n    password: antstar\n    database: 2\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: ruoyi-auth\n          uri: lb://ruoyi-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: ruoyi-gen\n          uri: lb://ruoyi-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: ruoyi-job\n          uri: lb://ruoyi-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: ruoyi-system\n          uri: lb://ruoyi-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 文件服务\n        - id: ruoyi-file\n          uri: lb://ruoyi-file\n          predicates:\n            - Path=/file/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', '3ff515fa29464d4ecd326b46ef4130b7', '2021-04-04 23:00:01', '2021-04-04 10:00:02', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (0, 39, 'cloud-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \n  redis:\n    host: 81.71.139.143\n    port: 8379\n    password: antstar\n    database: 2\n', '09564dc7ddcb01ae832df79f392263dd', '2021-04-04 23:06:25', '2021-04-04 10:06:23', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (3, 40, 'ruoyi-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \n  redis:\n    host: 81.71.139.143\n    port: 8379\n    password: antstar\n    database: 2\n', '09564dc7ddcb01ae832df79f392263dd', '2021-04-04 23:06:33', '2021-04-04 10:06:31', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (0, 41, 'cloud-monitor-dev.yml', 'DEFAULT_GROUP', '', '# spring\r\nspring: \r\n  security:\r\n    user:\r\n      name: ruoyi\r\n      password: 123456\r\n  boot:\r\n    admin:\r\n      ui:\r\n        title: 若依服务状态监控\r\n', 'd8997d0707a2fd5d9fc4e8409da38129', '2021-04-04 23:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 42, 'cloud-system-dev.yml', 'DEFAULT_GROUP', '', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource:\r\n    druid:\r\n      stat-view-servlet:\r\n        enabled: true\r\n        loginUsername: admin\r\n        loginPassword: 123456\r\n    dynamic:\r\n      druid:\r\n        initial-size: 5\r\n        min-idle: 5\r\n        maxActive: 20\r\n        maxWait: 60000\r\n        timeBetweenEvictionRunsMillis: 60000\r\n        minEvictableIdleTimeMillis: 300000\r\n        validationQuery: SELECT 1 FROM DUAL\r\n        testWhileIdle: true\r\n        testOnBorrow: false\r\n        testOnReturn: false\r\n        poolPreparedStatements: true\r\n        maxPoolPreparedStatementPerConnectionSize: 20\r\n        filters: stat,wall,slf4j\r\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\r\n      datasource:\r\n          # 主库数据源\r\n          master:\r\n            driver-class-name: com.mysql.cj.jdbc.Driver\r\n            url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            username: root\r\n            password: password\r\n          # 从库数据源\r\n          # slave:\r\n            # username: \r\n            # password: \r\n            # url: \r\n            # driver-class-name: \r\n      # seata: true    # 开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭\r\n\r\n# seata配置\r\nseata:\r\n  # 默认关闭，如需启用spring.datasource.dynami.seata需要同时开启\r\n  enabled: false\r\n  # Seata 应用编号，默认为 ${spring.application.name}\r\n  application-id: ${spring.application.name}\r\n  # Seata 事务组编号，用于 TC 集群名\r\n  tx-service-group: ${spring.application.name}-group\r\n  # 关闭自动代理\r\n  enable-auto-data-source-proxy: false\r\n  # 服务配置项\r\n  service:\r\n    # 虚拟组和分组的映射\r\n    vgroup-mapping:\r\n      ruoyi-system-group: default\r\n  config:\r\n    type: nacos\r\n    nacos:\r\n      serverAddr: 127.0.0.1:8848\r\n      group: SEATA_GROUP\r\n      namespace:\r\n  registry:\r\n    type: nacos\r\n    nacos:\r\n      application: seata-server\r\n      server-addr: 127.0.0.1:8848\r\n      namespace:\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.system\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip', 'ac8913dee679e65bb7d482df5f267d4e', '2021-04-04 23:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 43, 'cloud-gen-dev.yml', 'DEFAULT_GROUP', '', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource: \r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: password\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.gen.domain\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 代码生成接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n\r\n# 代码生成\r\ngen: \r\n  # 作者\r\n  author: ruoyi\r\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\r\n  packageName: com.ruoyi.system\r\n  # 自动去除表前缀，默认是false\r\n  autoRemovePre: false\r\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\r\n  tablePrefix: sys_\r\n', '8c79f64a4cca9b821a03dc8b27a2d8eb', '2021-04-04 23:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 44, 'cloud-job-dev.yml', 'DEFAULT_GROUP', '', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: password\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.job.domain\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 定时任务接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n', 'd6dfade9a2c93c463ae857cd503cb172', '2021-04-04 23:07:27', '2021-04-04 10:07:27', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (0, 45, 'cloud-file-dev.yml', 'DEFAULT_GROUP', '', '# 本地文件上传    \r\nfile:\r\n    domain: http://127.0.0.1:9300\r\n    path: D:/ruoyi/uploadPath\r\n    prefix: /statics\r\n\r\n# FastDFS配置\r\nfdfs:\r\n  domain: http://8.129.231.12\r\n  soTimeout: 3000\r\n  connectTimeout: 2000\r\n  trackerList: 8.129.231.12:22122\r\n\r\n# Minio配置\r\nminio:\r\n  url: http://8.129.231.12:9000\r\n  accessKey: minioadmin\r\n  secretKey: minioadmin\r\n  bucketName: test', '5382b93f3d8059d6068c0501fdd41195', '2021-04-04 23:07:28', '2021-04-04 10:07:27', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (4, 46, 'ruoyi-monitor-dev.yml', 'DEFAULT_GROUP', '', '# spring\r\nspring: \r\n  security:\r\n    user:\r\n      name: ruoyi\r\n      password: 123456\r\n  boot:\r\n    admin:\r\n      ui:\r\n        title: 若依服务状态监控\r\n', 'd8997d0707a2fd5d9fc4e8409da38129', '2021-04-04 23:07:36', '2021-04-04 10:07:36', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (5, 47, 'ruoyi-system-dev.yml', 'DEFAULT_GROUP', '', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource:\r\n    druid:\r\n      stat-view-servlet:\r\n        enabled: true\r\n        loginUsername: admin\r\n        loginPassword: 123456\r\n    dynamic:\r\n      druid:\r\n        initial-size: 5\r\n        min-idle: 5\r\n        maxActive: 20\r\n        maxWait: 60000\r\n        timeBetweenEvictionRunsMillis: 60000\r\n        minEvictableIdleTimeMillis: 300000\r\n        validationQuery: SELECT 1 FROM DUAL\r\n        testWhileIdle: true\r\n        testOnBorrow: false\r\n        testOnReturn: false\r\n        poolPreparedStatements: true\r\n        maxPoolPreparedStatementPerConnectionSize: 20\r\n        filters: stat,wall,slf4j\r\n        connectionProperties: druid.stat.mergeSql\\=true;druid.stat.slowSqlMillis\\=5000\r\n      datasource:\r\n          # 主库数据源\r\n          master:\r\n            driver-class-name: com.mysql.cj.jdbc.Driver\r\n            url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            username: root\r\n            password: password\r\n          # 从库数据源\r\n          # slave:\r\n            # username: \r\n            # password: \r\n            # url: \r\n            # driver-class-name: \r\n      # seata: true    # 开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭\r\n\r\n# seata配置\r\nseata:\r\n  # 默认关闭，如需启用spring.datasource.dynami.seata需要同时开启\r\n  enabled: false\r\n  # Seata 应用编号，默认为 ${spring.application.name}\r\n  application-id: ${spring.application.name}\r\n  # Seata 事务组编号，用于 TC 集群名\r\n  tx-service-group: ${spring.application.name}-group\r\n  # 关闭自动代理\r\n  enable-auto-data-source-proxy: false\r\n  # 服务配置项\r\n  service:\r\n    # 虚拟组和分组的映射\r\n    vgroup-mapping:\r\n      ruoyi-system-group: default\r\n  config:\r\n    type: nacos\r\n    nacos:\r\n      serverAddr: 127.0.0.1:8848\r\n      group: SEATA_GROUP\r\n      namespace:\r\n  registry:\r\n    type: nacos\r\n    nacos:\r\n      application: seata-server\r\n      server-addr: 127.0.0.1:8848\r\n      namespace:\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.system\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip', 'ac8913dee679e65bb7d482df5f267d4e', '2021-04-04 23:07:36', '2021-04-04 10:07:36', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (6, 48, 'ruoyi-gen-dev.yml', 'DEFAULT_GROUP', '', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource: \r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: password\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.gen.domain\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 代码生成接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n\r\n# 代码生成\r\ngen: \r\n  # 作者\r\n  author: ruoyi\r\n  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool\r\n  packageName: com.ruoyi.system\r\n  # 自动去除表前缀，默认是false\r\n  autoRemovePre: false\r\n  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）\r\n  tablePrefix: sys_\r\n', '8c79f64a4cca9b821a03dc8b27a2d8eb', '2021-04-04 23:07:36', '2021-04-04 10:07:36', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (7, 49, 'ruoyi-job-dev.yml', 'DEFAULT_GROUP', '', '# spring配置\r\nspring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: password\r\n\r\n# mybatis配置\r\nmybatis:\r\n    # 搜索指定包别名\r\n    typeAliasesPackage: com.ruoyi.job.domain\r\n    # 配置mapper的扫描，找到所有的mapper.xml映射文件\r\n    mapperLocations: classpath:mapper/**/*.xml\r\n\r\n# swagger配置\r\nswagger:\r\n  title: 定时任务接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n', 'd6dfade9a2c93c463ae857cd503cb172', '2021-04-04 23:07:36', '2021-04-04 10:07:36', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (8, 50, 'ruoyi-file-dev.yml', 'DEFAULT_GROUP', '', '# 本地文件上传    \r\nfile:\r\n    domain: http://127.0.0.1:9300\r\n    path: D:/ruoyi/uploadPath\r\n    prefix: /statics\r\n\r\n# FastDFS配置\r\nfdfs:\r\n  domain: http://8.129.231.12\r\n  soTimeout: 3000\r\n  connectTimeout: 2000\r\n  trackerList: 8.129.231.12:22122\r\n\r\n# Minio配置\r\nminio:\r\n  url: http://8.129.231.12:9000\r\n  accessKey: minioadmin\r\n  secretKey: minioadmin\r\n  bucketName: test', '5382b93f3d8059d6068c0501fdd41195', '2021-04-04 23:07:36', '2021-04-04 10:07:36', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (0, 51, 'cloud-gateway-sentinel.json', 'DEFAULT_GROUP', '', '[\r\n    {\r\n        \"resource\": \"ruoyi-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-system\",\r\n        \"count\": 1000,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-job\",\r\n        \"count\": 300,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]', '9f3a3069261598f74220bc47958ec252', '2021-04-04 23:08:41', '2021-04-04 10:08:42', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (9, 52, 'sentinel-ruoyi-gateway', 'DEFAULT_GROUP', '', '[\r\n    {\r\n        \"resource\": \"ruoyi-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-system\",\r\n        \"count\": 1000,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-job\",\r\n        \"count\": 300,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]', '9f3a3069261598f74220bc47958ec252', '2021-04-04 23:09:15', '2021-04-04 10:09:15', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (0, 53, 'cloud-gateway-sentinel', 'DEFAULT_GROUP', '', '[\r\n    {\r\n        \"resource\": \"ruoyi-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-system\",\r\n        \"count\": 1000,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-job\",\r\n        \"count\": 300,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]', '9f3a3069261598f74220bc47958ec252', '2021-04-04 23:09:40', '2021-04-04 10:09:41', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (41, 54, 'cloud-gateway-sentinel.json', 'DEFAULT_GROUP', '', '[\r\n    {\r\n        \"resource\": \"ruoyi-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-system\",\r\n        \"count\": 1000,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"ruoyi-job\",\r\n        \"count\": 300,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]', '9f3a3069261598f74220bc47958ec252', '2021-04-04 23:10:31', '2021-04-04 10:10:11', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (0, 55, 'cloud-common.yml', 'DEFAULT_GROUP', '', 'spring:\n  main:\n    allow-bean-definition-overriding: true\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n', 'c07e6f7321493f6d5390d0a08bffb75a', '2021-04-04 23:21:15', '2021-04-04 10:21:15', NULL, '172.18.0.1', 'I', '');
INSERT INTO `his_config_info` VALUES (1, 56, 'application-dev.yml', 'DEFAULT_GROUP', '', 'spring:\n  main:\n    allow-bean-definition-overriding: true\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n', 'c07e6f7321493f6d5390d0a08bffb75a', '2021-04-04 23:21:39', '2021-04-04 10:21:35', NULL, '172.18.0.1', 'D', '');
INSERT INTO `his_config_info` VALUES (0, 57, 'cloud-common.properties', 'DEFAULT_GROUP', '', 'spring:\n  main:\n    allow-bean-definition-overriding: true\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n', 'c07e6f7321493f6d5390d0a08bffb75a', '2021-04-04 23:24:36', '2021-04-04 10:24:36', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (44, 58, 'cloud-common.properties', 'DEFAULT_GROUP', '', 'spring:\n  main:\n    allow-bean-definition-overriding: true\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# feign 配置\nfeign:\n  sentinel:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n', 'c07e6f7321493f6d5390d0a08bffb75a', '2021-04-04 23:29:14', '2021-04-04 10:29:15', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 59, 'cloud-gateway.properties', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: 81.71.139.143\n    port: 8379\n    password: antstar\n    database: 2\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: ruoyi-auth\n          uri: lb://ruoyi-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: ruoyi-gen\n          uri: lb://ruoyi-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: ruoyi-job\n          uri: lb://ruoyi-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: ruoyi-system\n          uri: lb://ruoyi-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 文件服务\n        - id: ruoyi-file\n          uri: lb://ruoyi-file\n          predicates:\n            - Path=/file/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', '3ff515fa29464d4ecd326b46ef4130b7', '2021-04-04 23:30:07', '2021-04-04 10:30:07', NULL, '172.18.0.1', 'I', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (46, 60, 'cloud-gateway.properties', 'DEFAULT_GROUP', '', 'spring:\n  redis:\n    host: 81.71.139.143\n    port: 8379\n    password: antstar\n    database: 2\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          lowerCaseServiceId: true\n          enabled: true\n      routes:\n        # 认证中心\n        - id: ruoyi-auth\n          uri: lb://ruoyi-auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            # 验证码处理\n            - CacheRequestFilter\n            - ValidateCodeFilter\n            - StripPrefix=1\n        # 代码生成\n        - id: ruoyi-gen\n          uri: lb://ruoyi-gen\n          predicates:\n            - Path=/code/**\n          filters:\n            - StripPrefix=1\n        # 定时任务\n        - id: ruoyi-job\n          uri: lb://ruoyi-job\n          predicates:\n            - Path=/schedule/**\n          filters:\n            - StripPrefix=1\n        # 系统模块\n        - id: ruoyi-system\n          uri: lb://ruoyi-system\n          predicates:\n            - Path=/system/**\n          filters:\n            - StripPrefix=1\n        # 文件服务\n        - id: ruoyi-file\n          uri: lb://ruoyi-file\n          predicates:\n            - Path=/file/**\n          filters:\n            - StripPrefix=1\n\n# 不校验白名单\nignore:\n  whites:\n    - /auth/logout\n    - /auth/login\n    - /*/v2/api-docs\n    - /csrf\n', '3ff515fa29464d4ecd326b46ef4130b7', '2021-04-04 23:32:55', '2021-04-04 10:32:55', NULL, '172.18.0.1', 'U', '0dca6ba7-f031-4cf6-a4e7-b44d0d036a47');
INSERT INTO `his_config_info` VALUES (0, 61, 'cloud-common-redis.properties', 'DEFAULT_GROUP', '', 'spring.redis.host=81.71.139.143\r\nspring.redis.port=8379\r\nspring.redis.password=antstar\r\nspring.redis.database=2', '09fb48559f357d81702b0f051793b450', '2021-04-04 23:54:49', '2021-04-04 10:54:49', NULL, '172.18.0.1', 'I', 'b8ffe849-49ed-452f-86df-273cfc8301dc');
INSERT INTO `his_config_info` VALUES (0, 62, 'cloud-common-mybatis-plus.properties', 'DEFAULT_GROUP', '', '# xml 扫描路径\r\nmybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml\r\n\r\n# MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)\r\nmybatis-plus.typeAliasesPackage=com.fank243.cloud.component.domain.entity\r\n\r\n# 枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性\r\nmybatis-plus.typeEnumsPackage=com.fank243.cloud.component.domain.enums\r\n\r\n# # 全局默认主键类型，NONE：随机ID，默认值：ASSIGN_ID(雪花算法)\r\nmybatis-plus.global-config.db-configid-type=NONE\r\n\r\n# 表名前缀\r\nmybatis-plus.global-config.table-prefix=tb\r\n\r\n# 逻辑删除字段名称\r\nmybatis-plus.global-configlogic-delete-field=is_deleted \r\n\r\n # 字段验证策略之 insert,在 insert 的时候的字段验证策略\r\nmybatis-plus.global-configinsert-strategy=not_empty\r\n\r\n# 字段验证策略之 update,在 update 的时候的字段验证策略\r\nmybatis-plus.global-configupdate-strategy=not_empty \r\n\r\n# 开启Mybatis二级缓存，默认为 true\r\nmybatis-plus.configuration.cache-enabled=false\r\n', 'c832f393bc3ed731981c3b5dc6271a75', '2021-04-04 23:54:49', '2021-04-04 10:54:49', NULL, '172.18.0.1', 'I', 'b8ffe849-49ed-452f-86df-273cfc8301dc');
INSERT INTO `his_config_info` VALUES (0, 63, 'cloud-auth.properties', 'DEFAULT_GROUP', '', '# 数据源\r\nspring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.druid.url=jdbc:mysql://81.71.139.143:8306/cloud-auth\r\nspring.datasource.druid.username=root\r\nspring.datasource.druid.password=ZdyGYHeFlE1TvcOWw0iU', '3a1467cac417c0a430b7f2bbc427a1ab', '2021-04-04 23:54:49', '2021-04-04 10:54:49', NULL, '172.18.0.1', 'I', 'b8ffe849-49ed-452f-86df-273cfc8301dc');
INSERT INTO `his_config_info` VALUES (0, 64, 'cloud-common.properties', 'DEFAULT_GROUP', '', 'spring.main.allow-bean-definition-overriding=true\nspring.autoconfigure.exclude=com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon.ReadTimeout=10000\nribbon.ConnectTimeout=10000\n\n# feign 配置\nfeign.sentinel.enabled=true\nfeign.okhttp.enabled=true\nfeign.httpclient.enabled=false\nfeign.client.config.default.connectTimeout=10000\nfeign.client.config.default.readTimeout=10000\nfeign.compression.request.enabled=true\nfeign.compression.response.enabled=true\n\n# 暴露监控端点\nmanagement.endpoints.web.exposure.include=\'*\'\n', 'b62774df756eb9570ee7960d0ae2e86b', '2021-04-04 23:54:51', '2021-04-04 10:54:49', NULL, '172.18.0.1', 'I', 'b8ffe849-49ed-452f-86df-273cfc8301dc');
INSERT INTO `his_config_info` VALUES (0, 65, 'cloud-gateway.properties', 'DEFAULT_GROUP', '', 'spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true\nspring.cloud.gateway.discovery.locator.enabled=true\n      \n# 不校验白名单\nignore.whites=/auth/logout,/auth/login,/*/v2/api-docs,/csrf\n', '141244852bf27e125cbb9480406db317', '2021-04-04 23:54:51', '2021-04-04 10:54:49', NULL, '172.18.0.1', 'I', 'b8ffe849-49ed-452f-86df-273cfc8301dc');
INSERT INTO `his_config_info` VALUES (51, 66, 'cloud-common.properties', 'DEFAULT_GROUP', '', 'spring.main.allow-bean-definition-overriding=true\nspring.autoconfigure.exclude=com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon.ReadTimeout=10000\nribbon.ConnectTimeout=10000\n\n# feign 配置\nfeign.sentinel.enabled=true\nfeign.okhttp.enabled=true\nfeign.httpclient.enabled=false\nfeign.client.config.default.connectTimeout=10000\nfeign.client.config.default.readTimeout=10000\nfeign.compression.request.enabled=true\nfeign.compression.response.enabled=true\n\n# 暴露监控端点\nmanagement.endpoints.web.exposure.include=\'*\'\n', 'b62774df756eb9570ee7960d0ae2e86b', '2021-04-05 22:08:32', '2021-04-05 09:08:31', NULL, '172.18.0.1', 'U', 'b8ffe849-49ed-452f-86df-273cfc8301dc');
INSERT INTO `his_config_info` VALUES (51, 67, 'cloud-common.properties', 'DEFAULT_GROUP', '', 'spring.main.allow-bean-definition-overriding=true\nspring.autoconfigure.exclude=com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon.ReadTimeout=10000\nribbon.ConnectTimeout=10000\n\n# feign 配置\nfeign.sentinel.enabled=true\nfeign.okhttp.enabled=true\nfeign.httpclient.enabled=false\nfeign.client.config.default.connectTimeout=10000\nfeign.client.config.default.readTimeout=10000\nfeign.compression.request.enabled=true\nfeign.compression.response.enabled=true\n\n# 暴露监控端点\nmanagement.endpoints.web.exposure.include=\"*\"\n', 'cf396197c955387fb9cf07cced6cb8ea', '2021-04-05 22:17:44', '2021-04-05 09:17:43', NULL, '172.18.0.1', 'U', 'b8ffe849-49ed-452f-86df-273cfc8301dc');
INSERT INTO `his_config_info` VALUES (51, 68, 'cloud-common.properties', 'DEFAULT_GROUP', '', 'spring.main.allow-bean-definition-overriding=true\nspring.autoconfigure.exclude=com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon.ReadTimeout=10000\nribbon.ConnectTimeout=10000\n\n# feign 配置\nfeign.sentinel.enabled=true\nfeign.okhttp.enabled=true\nfeign.httpclient.enabled=false\nfeign.client.config.default.connectTimeout=10000\nfeign.client.config.default.readTimeout=10000\nfeign.compression.request.enabled=true\nfeign.compression.response.enabled=true\n\n# 暴露监控端点\nmanagement.endpoints.web.exposure.include=*\n', '293b42192bd132d1b69b04f69c6ee8dd', '2021-04-05 22:19:32', '2021-04-05 09:19:32', NULL, '172.18.0.1', 'U', 'b8ffe849-49ed-452f-86df-273cfc8301dc');
INSERT INTO `his_config_info` VALUES (51, 69, 'cloud-common.properties', 'DEFAULT_GROUP', '', 'spring.main.allow-bean-definition-overriding=true\nspring.autoconfigure.exclude=com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n\n#请求处理的超时时间\nribbon.ReadTimeout=10000\nribbon.ConnectTimeout=10000\n\n# feign 配置\nfeign.sentinel.enabled=true\nfeign.okhttp.enabled=true\nfeign.httpclient.enabled=false\nfeign.client.config.default.connectTimeout=10000\nfeign.client.config.default.readTimeout=10000\nfeign.compression.request.enabled=true\nfeign.compression.response.enabled=true\n\n# 暴露监控端点\nmanagement.endpoints.web.exposure.include=\"*\"\n', 'cf396197c955387fb9cf07cced6cb8ea', '2021-04-05 22:20:49', '2021-04-05 09:20:48', NULL, '172.18.0.1', 'U', 'b8ffe849-49ed-452f-86df-273cfc8301dc');

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions`  (
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `resource` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `action` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  UNIQUE INDEX `uk_role_permission`(`role`, `resource`, `action`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of permissions
-- ----------------------------

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  UNIQUE INDEX `idx_user_role`(`username`, `role`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(20) NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint(20) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
INSERT INTO `tenant_info` VALUES (2, '1', 'b8ffe849-49ed-452f-86df-273cfc8301dc', 'cloud', 'cloud', 'nacos', 1617551653073, 1617551653073);

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

SET FOREIGN_KEY_CHECKS = 1;
